apiVersion: apps/v1
kind: Deployment

metadata: 
  name: flask-demo

specs:
  replicas: 2

  seletor:
    matchLabels:
      app: flask-demo

  template:

    metadata:
      labels:
        app: flask-demo

    spec:

      containers:
      - name: flask-demo
        image: flask-demo:latest

        imagePullPolicy: Never

        ports:
        - containerPort: 5000